name: SSBOneBlock
version: ${project.version}
api-version: "1.13"
author: Ome_R
depend: [SuperiorSkyblock2]
main: com.bgsoftware.ssboneblock.OneBlockPlugin

commands:
  oneblock:
    aliases: [ob]
    description: Main command for the plugin.

permissions:
  oneblock.*:
    description: Gives access to all the command.
    default: op
    children:
      oneblock.check: true
      oneblock.reload: true
      oneblock.save: true
      oneblock.setphase: true
      oneblock.setphaseblock: true
  oneblock.check:
    description: Check progress of a player.
  oneblock.reload:
    description: Reload all settings of the plugin.
  oneblock.save:
    description: Save all data to disk.
  oneblock.setphase:
    description: Set the phase for a specific player.
  oneblock.setphaseblock:
    description: Set the phase-block for a specific player.